### ISSUE TITLE
Make 2 simpler repos  instead one huge

### ISSUE THREAD

**Issue by 3lvis** [kostiakoval/Sweet#2]

**Comment by kostiakoval** [comment]
Good issue :) 
I'm thinking of making 2 repos, 1 for File management and other from App info 
Thanks for contribution 

![Giphy](http://media2.giphy.com/media/Q4VJp9X04TDDG/giphy.gif)

**Comment by 3lvis** [comment]
\o/

**Comment by 3lvis** [comment]
Would make it easier to test and document.

**Comment by kostiakoval** [comment]
It's not done yet so I would keep this issue open.

**Comment by 3lvis** [comment]
:heart:

**Comment by 3lvis** [comment]
Closing old issues, since they might not be relevant.
